   
services:
    imocontrol.customer:
      class: %imocontrol.customer.admin.class%
      tags:
        - { name: sonata.admin, manager_type: orm, group: Customers, label: customer_title, persist_filters: true }
      arguments: [null, %imocontrol.customer.admin.entity.class%, %imocontrol.customer.admin.controller.class%]
      calls:
        - [setSecurityContext, [@security.context]]
        
    imocontrol.customer_address:
      class: %imocontrol.customer_address.admin.class%
      tags:
        - { name: sonata.admin, manager_type: orm, group: Customers, label: customer_address_title, persist_filters: true }
      arguments: [null, %imocontrol.customer_address.admin.entity.class%, %imocontrol.customer.admin.controller.class%]
      calls:
        - [setSecurityContext, [@security.context]]
        
    imocontrol.contact:
      class: %imocontrol.contact.admin.class%
      tags:
        - { name: sonata.admin, manager_type: orm, group: Customers, label: customer_contact_title, persist_filters: true }
      arguments: [null, %imocontrol.contact.admin.entity.class%, %imocontrol.customer.admin.controller.class%]
      calls:
        - [setSecurityContext, [@security.context]]
